
pipeline{
    agent any
	stages{

        Stage("Step 1") {
            steps {
                // In the jenkinsVM, sign into DockerHub and Kubectl (as jenkins user?)
            }
        }
        Stage("Step 2") {
            steps {
                //Docker compose up -d (to build all the images (frontend and backend))
            }
        }
        Stage("Step 3") {
            steps {
                //step three here
            }
        }
    }
}