
pipeline{
    agent any
    withCredentials(bindings: [usernamePassword(credentialsId: 'Nexus', \ passwordVariable: 'NexusPassword', \ usernameVariable: 'NexusUser'), usernamePassword(credentialsId: 'awsKeys', \ passwordVariable: 'awsSecretKey', \ usernameVariable: 'awsKey'), string(credentialsId: 'NexusIP', \ variable: 'NexusIP')]) {
    // some block
    }
	stages{

        stage("Step 1") {
            steps {
                // In the jenkinsVM, sign into DockerHub and Kubectl (as jenkins user?)
                sh 'bash ./App/Scripts/logins.sh'
            }
        }
        stage("Step 2") {
            steps {
                //Docker compose up -d (to build all the images (frontend and backend))
                sh 'cd ~/QA-TP-G2/App/'
                sh 'docker-compose up -d'
            }
        }
        stage("Run the backend and frontend tests") {
            steps {
                // Run the tests (npm test for frontend) (somehow test backend)
                sh 'bash ./App/Scripts/frontend-tests.sh'
                sh 'bash ./App/Scripts/backend-tests.sh'
            }
        }
        stage("Push the successful images to nexus repo") {
            steps {
                // Pushing the images ran to nexus repository
                sh 'bash ./App/Scripts/image-push.sh'
            }
        }
        stage("Update the Kubernetes files") {
            steps {
                // Updating the kubernetes files (deployments, services, configmap, secrets) to pull latest image
                sh 'bash ./App/Scripts/...'
            }
        }
    }
}

